# Usa uma imagem base oficial do Python para o seu projeto
FROM python:3.11-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo de dependências e o instala primeiro para otimizar o cache do Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da sua aplicação para o contêiner
COPY . .

# Expõe a porta que o FastAPI vai usar (8000)
EXPOSE 8000

# Comando para iniciar o servidor Uvicorn quando o contêiner for executado
# "--host 0.0.0.0" é necessário para que o servidor seja acessível de fora do contêiner
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]